version = 1

[[analyzers]]
name = "shell"

[[analyzers]]
name = "javascript"

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"
  [analyzers.config]
  exclude_patterns = [
    "migrations/"
  ]
